services:
  kafka:
    image: apache/kafka:latest
    environment:
      - KAFKA_LISTENERS=CONTROLLER://localhost:9091,DOCKER://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=DOCKER://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9091
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_NUM_PARTITIONS=1
    networks:
      - kafka-network
    restart: unless-stopped

networks:
  kafka-network:
    name: kafka-network
    external: true
