services:
  kafka:
    image: apache/kafka:latest
    env_file:
      - .env
    networks:
      - kafka-network
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: unless-stopped

  register-kafka:
    build: .
    networks:
      - kafka-network
    depends_on:
      - kafka

networks:
  kafka-network:
    driver: bridge

volumes:
  kafka-data:
